export type Tab = "topics" | "interview" | "vocab";

export const RANDOM_TRACK = "Random Mix";

export const TOPIC_CATEGORIES = [
  RANDOM_TRACK,
  "India & Politics",
  "Bollywood",
  "Cricket",
  "Tech & AI 2026",
  "Gen-Z Culture",
  "Startups",
  "Global Affairs",
  "Climate & Cities",
] as const;

export const TOPICS: Record<string, string[]> = {
  "India & Politics": [
    "Should voting be made mandatory in India?",
    "One Nation, One Election — democratic upgrade or centralisation?",
    "Free electricity schemes: empowerment or vote-bank politics?",
    "Should India shift to a presidential system?",
    "Regional parties are crucial for true federalism.",
    "Lateral entry into IAS will fix bureaucracy.",
    "Caste census in 2026 — overdue or divisive?",
    "Should MPs face mandatory recall after 3 years of underperformance?",
    "Uniform Civil Code: justice or majoritarianism?",
    "Should India lower the voting age to 16?",
    "Privatising loss-making PSUs is non-negotiable for growth.",
    "Should political party funding be 100% state-funded?",
  ],
  "Bollywood": [
    "South Indian cinema has officially out-shadowed Bollywood.",
    "Nepotism in Bollywood is overrated as a debate.",
    "OTT killed the theatrical experience in India.",
    "Item songs need to be banned from mainstream cinema.",
    "Pan-India films are killing regional storytelling.",
    "Bollywood remakes of South hits are creatively bankrupt.",
    "Actor fees should be capped relative to film budget.",
    "Censor board should be replaced with an industry rating body.",
    "Animal-style hyper-masculine films are a cultural regression.",
    "Streaming platforms should be forced to release India-first originals.",
  ],
  "Cricket": [
    "IPL has destroyed the spirit of Test cricket.",
    "Impact Player rule is ruining T20 strategy.",
    "Indian cricketers are paid disproportionately to other sports.",
    "Captaincy should rotate across formats.",
    "Two-tier Test cricket will save the format.",
    "T20 World Cup every two years dilutes the trophy.",
    "DRS should be removed — it kills umpire authority.",
    "Women's IPL needs equal pay with men's IPL by 2027.",
    "Franchise leagues are bigger than international cricket now.",
    "Bilateral ODIs should be scrapped outside World Cup years.",
  ],
  "Tech & AI 2026": [
    "AI will create more jobs than it destroys in India.",
    "UPI's success makes India ready to export digital infrastructure.",
    "WFH is a long-term net negative for fresh graduates.",
    "India should ban crypto outright.",
    "Generative AI in classrooms will collapse critical thinking.",
    "India needs a sovereign LLM funded by the government.",
    "Deepfake political ads should be a criminal offence.",
    "AI agents will replace 30% of entry-level white-collar jobs by 2028.",
    "Aadhaar should be optional for all private services.",
    "Social media should require verified ID by law.",
    "Self-driving cars will never work on Indian roads.",
    "Quick commerce (10-min delivery) is socially harmful.",
  ],
  "Gen-Z Culture": [
    "Influencer culture is corroding professional ambition.",
    "Dating apps have killed real romance in metro cities.",
    "Hustle culture is overrated.",
    "Anonymous apps do more harm than good on campus.",
    "Therapy-speak on Instagram is making us worse, not better.",
    "Soft-launching relationships is emotional cowardice.",
    "Gen-Z quitting jobs in 6 months is a feature, not a flaw.",
    "Short-form video is rewiring student attention span beyond repair.",
    "Astrology apps should carry mental-health warnings.",
    "Performative activism on stories does more harm than silence.",
  ],
  "Startups": [
    "Indian startups should focus on profitability over GMV.",
    "ESOPs are overrated as a wealth creation tool.",
    "Bharat-first startups will outperform India-first ones.",
    "Edtech in India is a bubble waiting to pop.",
    "D2C brands are just glorified marketing arbitrage.",
    "Founders taking secondaries before profitability is a red flag.",
    "VC-funded growth is incompatible with sustainable businesses.",
    "India needs a startup-specific bankruptcy code.",
    "Quick-commerce unit economics will never work outside metros.",
    "Reverse-flipping back to India is a tax play, not patriotism.",
  ],
  "Global Affairs": [
    "India should formally pick a side in the US-China rivalry.",
    "BRICS currency is a fantasy.",
    "India deserves a permanent UNSC seat in this decade.",
    "Climate reparations from the West are non-negotiable.",
    "Israel-Palestine should not be India's diplomatic concern.",
    "Russia is no longer a reliable defence partner for India.",
    "Open borders within South Asia would boost the region's GDP.",
  ],
  "Climate & Cities": [
    "Delhi's winter air is a national emergency, not a city problem.",
    "Private vehicles should be banned in city cores by 2030.",
    "Bengaluru has already failed as an urban experiment.",
    "Coal phase-out must wait — energy security comes first.",
    "Every Indian metro needs congestion pricing now.",
    "Building height limits should be scrapped to fix housing.",
    "Free public transport for women is good policy, not pandering.",
  ],
};

export const INTERVIEW_CATEGORIES = [
  "Behavioral (Top 50)",
  "Product Management",
  "Consulting Guesstimates",
  "Engineering / Tech",
  "MBA Admissions",
  "Finance & IB",
  "Sales & Marketing",
] as const;

export const INTERVIEW_QUESTIONS: Record<string, string[]> = {
  "Behavioral (Top 50)": [
    "Tell me about yourself in 90 seconds.",
    "Walk me through your resume.",
    "Why should we hire you over someone with more experience?",
    "What are your three biggest strengths — with proof?",
    "What is your biggest weakness and how are you fixing it?",
    "Tell me about a time you led a team through conflict.",
    "Describe your biggest failure and what you learned.",
    "Tell me about a time you disagreed with a manager.",
    "Tell me about a time you missed a deadline.",
    "Describe a time you had to give difficult feedback.",
    "Tell me about a time you received harsh criticism.",
    "Walk me through your proudest professional achievement.",
    "Tell me about a time you had to influence without authority.",
    "Describe a time you took initiative beyond your role.",
    "Tell me about a time you had to learn something fast.",
    "Describe a time you made a decision with incomplete data.",
    "Tell me about a time you mentored someone.",
    "Describe a time you handled an angry stakeholder.",
    "Tell me about a time you had to say no to your boss.",
    "Describe a time you turned around a failing project.",
    "Tell me about a time you worked with a difficult teammate.",
    "Describe a time you prioritised under heavy workload.",
    "Tell me about a time your ethics were tested at work.",
    "Walk me through a time you had to fire or remove someone.",
    "Describe the toughest stakeholder you've managed.",
    "Tell me about a time you simplified a complex process.",
    "Describe a time you used data to change someone's mind.",
    "Tell me about a time you took a calculated risk.",
    "Describe a time you broke a rule for the right reason.",
    "Tell me about a time you handled ambiguity well.",
    "Describe a cross-functional project you led end-to-end.",
    "Tell me about a time you missed a target — what next?",
    "Describe a time you negotiated a tough outcome.",
    "Tell me about a time you onboarded into a new team fast.",
    "Describe a time you challenged the status quo.",
    "Tell me about a time your idea was shot down — what did you do?",
    "Describe a time you spotted a problem nobody else saw.",
    "Tell me about a time you delivered under extreme pressure.",
    "Describe a time you balanced quality vs speed.",
    "Tell me about a time you had to fix someone else's mistake.",
    "Describe your most creative solution to a work problem.",
    "Tell me about a time you turned a critic into an ally.",
    "Describe a time you owned a failure publicly.",
    "Tell me about a time you scaled a process or team.",
    "Describe your leadership style with one example.",
    "Tell me about a time you had to deliver bad news.",
    "Describe a time you had to defend an unpopular decision.",
    "Tell me about a time you collaborated remotely under chaos.",
    "Why are you leaving your current role?",
    "Where do you see yourself in five years?",
  ],
  "Product Management": [
    "How would you improve Instagram Reels for India?",
    "Design a product for daily-wage workers in India.",
    "Estimate the market size of food delivery in Tier-2 cities.",
    "Your favorite product and how you'd 10x it.",
    "Design a Swiggy feature for solo diners.",
    "How would you reduce churn for Disney+ Hotstar in India?",
    "Design YouTube Shorts for users aged 50+.",
    "How would you onboard first-time UPI users in rural India?",
    "Pick a metric for Zomato Dining-Out and defend it.",
    "How would you prioritise three features for Ola Electric?",
    "Design WhatsApp Pay for small kirana stores.",
    "What's wrong with Aadhaar-based eKYC UX? Fix it.",
    "How would you grow LinkedIn's Indian student segment?",
    "Build a feature to fight misinformation on WhatsApp groups.",
    "How would you measure success of Spotify's regional playlists?",
    "Design a personal finance app for Gen-Z college students.",
  ],
  "Consulting Guesstimates": [
    "How many auto-rickshaws operate in Mumbai daily?",
    "Estimate the annual revenue of a single Starbucks in Bengaluru.",
    "How many WhatsApp messages are sent in India per second?",
    "Size the market for online tutoring in India.",
    "Estimate the daily petrol consumption in Delhi.",
    "How many haircuts happen in India every day?",
    "Size the wedding industry in India for 2026.",
    "Estimate the number of cricket bats sold in India per year.",
    "How many EV two-wheelers will sell in India in 2027?",
    "Size the dog-food market in urban India.",
    "Estimate ad revenue per IPL match.",
    "How many flights take off from Indian airports daily?",
    "Size the second-hand smartphone market in India.",
    "Estimate India's annual paneer consumption.",
  ],
  "Engineering / Tech": [
    "Explain a complex technical project to a non-technical person.",
    "How do you prioritize tech debt vs new features?",
    "Walk me through how you'd debug a production outage.",
    "Design the system behind UPI at a high level.",
    "How would you architect a chat app for 100M users?",
    "Explain CAP theorem with a real product example.",
    "How do you decide between SQL and NoSQL?",
    "Walk me through your code review philosophy.",
    "How would you handle a P0 bug on a Friday night?",
    "Explain microservices vs monolith to a CEO.",
    "How do you stay current with technology?",
    "Describe your testing strategy on your last project.",
  ],
  "MBA Admissions": [
    "Why MBA, why now, why this school?",
    "Describe a time you demonstrated leadership outside work.",
    "What is your long-term career vision?",
    "What will you contribute to our cohort that nobody else will?",
    "Walk me through your post-MBA five-year plan.",
    "What is one thing your recommenders won't tell us about you?",
    "Tell me about a setback that shaped you.",
    "Why this specific school and not its closest competitor?",
    "Describe your most international experience.",
    "What does ethical leadership mean to you?",
    "Which class or club will you contribute to in year one?",
    "How will you fund the MBA?",
  ],
  "Finance & IB": [
    "Walk me through a DCF.",
    "Why investment banking and not consulting?",
    "Walk me through the three financial statements.",
    "Pitch me a stock you'd buy today.",
    "What's your view on the Indian banking sector right now?",
    "Explain EV/EBITDA to a non-finance friend.",
    "How would RBI rate cuts impact NBFCs?",
    "What recent M&A deal interested you and why?",
    "How do you value a loss-making startup?",
    "Walk me through an LBO at a high level.",
  ],
  "Sales & Marketing": [
    "Sell me this pen.",
    "Walk me through your largest deal closed.",
    "How do you handle a flat 'no' from a buyer?",
    "Design a launch plan for a ₹999 protein bar in India.",
    "How would you grow a D2C skincare brand from ₹1Cr to ₹10Cr ARR?",
    "What's the difference between brand and performance marketing?",
    "How do you measure marketing ROI honestly?",
    "Pitch our product to a 55-year-old CFO in 30 seconds.",
    "What's a campaign you admired in the last year and why?",
    "How would you reduce CAC by 30% in a quarter?",
  ],
};

export const FRAMEWORKS = [
  {
    id: "star",
    name: "STAR",
    color: "bg-yappr-yellow",
    steps: [
      { k: "S", t: "Situation", d: "Set the scene in 1 sentence." },
      { k: "T", t: "Task", d: "What needed to be done? Your responsibility." },
      { k: "A", t: "Action", d: "Specific steps YOU took. Use 'I', not 'we'." },
      { k: "R", t: "Result", d: "Quantified outcome. Numbers, %, impact." },
    ],
  },
  {
    id: "prep",
    name: "PREP",
    color: "bg-yappr-blue",
    steps: [
      { k: "P", t: "Point", d: "State your core argument upfront." },
      { k: "R", t: "Reason", d: "Why is this point true?" },
      { k: "E", t: "Example", d: "One concrete example or data point." },
      { k: "P", t: "Point", d: "Restate the original point, sharper." },
    ],
  },
  {
    id: "ppf",
    name: "PPF",
    color: "bg-yappr-magenta",
    steps: [
      { k: "P", t: "Past", d: "Historical context — how did we get here?" },
      { k: "P", t: "Present", d: "Current state — what's happening now?" },
      { k: "F", t: "Future", d: "Where this is going + your stance." },
    ],
  },
] as const;

export const VOCAB_DECKS = [
  RANDOM_TRACK,
  "GRE Power Words",
  "Corporate Boardroom",
  "SAT Essentials",
  "Consulting Lingo",
] as const;

export type VocabWord = { word: string; ipa: string; pos: string; def: string; ex: string };

export const VOCAB_WORDS: Record<string, VocabWord[]> = {
  "GRE Power Words": [
    { word: "Ubiquitous", ipa: "/juːˈbɪkwɪtəs/", pos: "adj.", def: "Present everywhere.", ex: "Smartphones are now ubiquitous in urban India." },
    { word: "Ephemeral", ipa: "/ɪˈfɛmərəl/", pos: "adj.", def: "Lasting a very short time.", ex: "Viral fame is often ephemeral." },
    { word: "Pragmatic", ipa: "/præɡˈmætɪk/", pos: "adj.", def: "Dealing with things sensibly and realistically.", ex: "We need a pragmatic approach, not idealism." },
    { word: "Cogent", ipa: "/ˈkoʊdʒənt/", pos: "adj.", def: "Clear, logical, and convincing.", ex: "She made a cogent argument for remote work." },
    { word: "Perfunctory", ipa: "/pərˈfʌŋktəri/", pos: "adj.", def: "Done with minimum effort.", ex: "His perfunctory apology fooled nobody." },
    { word: "Sycophant", ipa: "/ˈsɪkəfænt/", pos: "noun", def: "A person who flatters to gain advantage.", ex: "The boardroom was full of sycophants." },
    { word: "Quixotic", ipa: "/kwɪkˈsɒtɪk/", pos: "adj.", def: "Wildly idealistic and impractical.", ex: "Reforming the system felt quixotic." },
    { word: "Sanguine", ipa: "/ˈsæŋɡwɪn/", pos: "adj.", def: "Optimistic, especially in difficulty.", ex: "She remained sanguine despite the layoffs." },
    { word: "Laconic", ipa: "/ləˈkɒnɪk/", pos: "adj.", def: "Using very few words.", ex: "His laconic reply ended the debate." },
    { word: "Obfuscate", ipa: "/ˈɒbfəskeɪt/", pos: "verb", def: "Make unclear, deliberately.", ex: "Politicians obfuscate to dodge accountability." },
    { word: "Ostensible", ipa: "/ɒˈstɛnsɪbl/", pos: "adj.", def: "Stated but not necessarily true.", ex: "The ostensible reason was a budget cut." },
    { word: "Recalcitrant", ipa: "/rɪˈkælsɪtrənt/", pos: "adj.", def: "Stubbornly uncooperative.", ex: "A recalcitrant team derailed the launch." },
    { word: "Salient", ipa: "/ˈseɪliənt/", pos: "adj.", def: "Most notable or important.", ex: "Cost was the salient issue in the room." },
    { word: "Tenuous", ipa: "/ˈtɛnjuəs/", pos: "adj.", def: "Very weak or slight.", ex: "The link between the two events is tenuous." },
    { word: "Vacuous", ipa: "/ˈvækjuəs/", pos: "adj.", def: "Lacking thought or substance.", ex: "His pitch was loud but vacuous." },
    { word: "Pernicious", ipa: "/pərˈnɪʃəs/", pos: "adj.", def: "Having harmful effect, gradually.", ex: "Doomscrolling has a pernicious effect on focus." },
    { word: "Equivocate", ipa: "/ɪˈkwɪvəkeɪt/", pos: "verb", def: "Speak ambiguously to mislead.", ex: "Stop equivocating — give me a yes or no." },
    { word: "Iconoclast", ipa: "/aɪˈkɒnəklæst/", pos: "noun", def: "Someone who challenges norms.", ex: "Steve Jobs was a true iconoclast." },
    { word: "Magnanimous", ipa: "/mæɡˈnænɪməs/", pos: "adj.", def: "Generous, especially toward rivals.", ex: "Her magnanimous concession won fans." },
    { word: "Nebulous", ipa: "/ˈnɛbjʊləs/", pos: "adj.", def: "Vague, ill-defined.", ex: "The roadmap was nebulous at best." },
    { word: "Polemic", ipa: "/pəˈlɛmɪk/", pos: "noun", def: "A strong verbal attack on a view.", ex: "His op-ed read like a polemic." },
    { word: "Surreptitious", ipa: "/ˌsʌrəpˈtɪʃəs/", pos: "adj.", def: "Kept secret because improper.", ex: "She took a surreptitious glance at the screen." },
    { word: "Vicarious", ipa: "/vɪˈkɛəriəs/", pos: "adj.", def: "Felt through someone else's experience.", ex: "He gets vicarious thrills from F1." },
    { word: "Zeitgeist", ipa: "/ˈzaɪtɡaɪst/", pos: "noun", def: "Spirit of the times.", ex: "AI agents capture the 2026 zeitgeist." },
    { word: "Ameliorate", ipa: "/əˈmiːliəreɪt/", pos: "verb", def: "Make a bad situation better.", ex: "The new policy may ameliorate traffic." },
    { word: "Capricious", ipa: "/kəˈprɪʃəs/", pos: "adj.", def: "Unpredictable, sudden changes.", ex: "Markets are capricious in election years." },
    { word: "Didactic", ipa: "/daɪˈdæktɪk/", pos: "adj.", def: "Intended to teach, often morally.", ex: "His tone was too didactic for a peer." },
    { word: "Esoteric", ipa: "/ˌɛsəˈtɛrɪk/", pos: "adj.", def: "Understood by a small group.", ex: "The reference was too esoteric for the room." },
    { word: "Fastidious", ipa: "/fæˈstɪdiəs/", pos: "adj.", def: "Very attentive to detail.", ex: "She is fastidious about brand guidelines." },
    { word: "Gregarious", ipa: "/ɡrɪˈɡɛəriəs/", pos: "adj.", def: "Sociable, fond of company.", ex: "A gregarious founder is a sales asset." },
  ],
  "Corporate Boardroom": [
    { word: "Synergy", ipa: "/ˈsɪnərdʒi/", pos: "noun", def: "Combined effect greater than sum of parts.", ex: "The merger created real synergy across teams." },
    { word: "Leverage", ipa: "/ˈlɛvərɪdʒ/", pos: "verb", def: "Use to maximum advantage.", ex: "We must leverage our brand equity." },
    { word: "Bandwidth", ipa: "/ˈbændwɪdθ/", pos: "noun", def: "Capacity to handle work.", ex: "I don't have the bandwidth this quarter." },
    { word: "Streamline", ipa: "/ˈstriːmlaɪn/", pos: "verb", def: "Make more efficient.", ex: "We streamlined onboarding to two days." },
    { word: "Scalable", ipa: "/ˈskeɪləbl/", pos: "adj.", def: "Able to grow without breaking.", ex: "The model isn't scalable past 10x." },
    { word: "Pivot", ipa: "/ˈpɪvət/", pos: "verb", def: "Change direction strategically.", ex: "We pivoted from B2C to B2B in 2025." },
    { word: "Runway", ipa: "/ˈrʌnweɪ/", pos: "noun", def: "Months of cash before zero.", ex: "We have 14 months of runway left." },
    { word: "Cadence", ipa: "/ˈkeɪdəns/", pos: "noun", def: "Rhythm of recurring work.", ex: "Let's set a weekly cadence for syncs." },
    { word: "Stakeholder", ipa: "/ˈsteɪkhoʊldər/", pos: "noun", def: "Anyone with interest in the outcome.", ex: "Every stakeholder needs a single owner." },
    { word: "Deliverable", ipa: "/dɪˈlɪvərəbl/", pos: "noun", def: "A concrete output owed to someone.", ex: "Friday's deliverable is the deck v2." },
    { word: "Granular", ipa: "/ˈɡrænjələr/", pos: "adj.", def: "Detailed at a fine level.", ex: "Give me a granular cost breakdown." },
    { word: "Iterate", ipa: "/ˈɪtəreɪt/", pos: "verb", def: "Improve through repeated cycles.", ex: "We'll iterate on the prototype weekly." },
    { word: "Mandate", ipa: "/ˈmændeɪt/", pos: "noun", def: "Official authority to act.", ex: "I don't have the mandate for layoffs." },
    { word: "Optics", ipa: "/ˈɒptɪks/", pos: "noun", def: "How a decision looks publicly.", ex: "The optics of that bonus are terrible." },
    { word: "Paradigm", ipa: "/ˈpærədaɪm/", pos: "noun", def: "Dominant model of thinking.", ex: "AI is shifting the SaaS paradigm." },
    { word: "Quorum", ipa: "/ˈkwɔːrəm/", pos: "noun", def: "Minimum needed to vote.", ex: "We didn't hit quorum, decision deferred." },
    { word: "Robust", ipa: "/roʊˈbʌst/", pos: "adj.", def: "Strong and reliable.", ex: "We need a robust QA pipeline." },
    { word: "Synthesise", ipa: "/ˈsɪnθəsaɪz/", pos: "verb", def: "Combine insights into one whole.", ex: "Synthesise the feedback into 3 themes." },
    { word: "Tractable", ipa: "/ˈtræktəbl/", pos: "adj.", def: "Manageable, solvable.", ex: "Break it into tractable problems first." },
    { word: "Validate", ipa: "/ˈvælɪdeɪt/", pos: "verb", def: "Confirm with evidence.", ex: "Validate the demand before building." },
    { word: "Whitespace", ipa: "/ˈwaɪtspeɪs/", pos: "noun", def: "Unserved market opportunity.", ex: "There's whitespace in tier-3 logistics." },
    { word: "Backchannel", ipa: "/ˈbækˌtʃænəl/", pos: "noun", def: "Informal communication route.", ex: "I'll backchannel the CFO before the meeting." },
    { word: "Cannibalise", ipa: "/ˈkænɪbəlaɪz/", pos: "verb", def: "Eat into own sales.", ex: "The new SKU will cannibalise the premium one." },
    { word: "Headwind", ipa: "/ˈhɛdwɪnd/", pos: "noun", def: "External force slowing growth.", ex: "Rate hikes are a real headwind." },
    { word: "Tailwind", ipa: "/ˈteɪlwɪnd/", pos: "noun", def: "External force boosting growth.", ex: "UPI is a tailwind for every fintech." },
    { word: "Materially", ipa: "/məˈtɪəriəli/", pos: "adv.", def: "In a significant, measurable way.", ex: "This will materially impact Q3 numbers." },
    { word: "Cohort", ipa: "/ˈkoʊhɔːrt/", pos: "noun", def: "A group tracked over time.", ex: "The Jan cohort retains 12% better." },
    { word: "Burn", ipa: "/bɜːrn/", pos: "noun", def: "Monthly cash spent.", ex: "Our burn dropped to ₹40L this month." },
    { word: "Greenfield", ipa: "/ˈɡriːnfiːld/", pos: "adj.", def: "Brand-new, no legacy.", ex: "It's a greenfield project — go bold." },
    { word: "Sunset", ipa: "/ˈsʌnsɛt/", pos: "verb", def: "Phase out a product.", ex: "We sunset the legacy app in March." },
  ],
  "SAT Essentials": [
    { word: "Candid", ipa: "/ˈkændɪd/", pos: "adj.", def: "Truthful and straightforward.", ex: "His candid feedback changed our roadmap." },
    { word: "Mitigate", ipa: "/ˈmɪtɪɡeɪt/", pos: "verb", def: "Make less severe.", ex: "We added tests to mitigate regressions." },
    { word: "Arduous", ipa: "/ˈɑːrdʒuəs/", pos: "adj.", def: "Requiring great effort.", ex: "The trek was arduous but worth it." },
    { word: "Benevolent", ipa: "/bəˈnɛvələnt/", pos: "adj.", def: "Kind and well-meaning.", ex: "A benevolent mentor changed her career." },
    { word: "Concise", ipa: "/kənˈsaɪs/", pos: "adj.", def: "Brief and clear.", ex: "Keep the answer concise — under 60 seconds." },
    { word: "Diligent", ipa: "/ˈdɪlɪdʒənt/", pos: "adj.", def: "Hard-working and careful.", ex: "She's the most diligent intern we've had." },
    { word: "Elated", ipa: "/ɪˈleɪtɪd/", pos: "adj.", def: "Extremely happy.", ex: "We were elated by the funding news." },
    { word: "Frugal", ipa: "/ˈfruːɡəl/", pos: "adj.", def: "Careful with money.", ex: "Frugal founders survive longer." },
    { word: "Hostile", ipa: "/ˈhɒstaɪl/", pos: "adj.", def: "Unfriendly, antagonistic.", ex: "The room turned hostile after the pricing slide." },
    { word: "Ingenious", ipa: "/ɪnˈdʒiːniəs/", pos: "adj.", def: "Clever and original.", ex: "An ingenious workaround saved the demo." },
    { word: "Jovial", ipa: "/ˈdʒoʊviəl/", pos: "adj.", def: "Cheerful and friendly.", ex: "His jovial tone disarmed the panel." },
    { word: "Lucid", ipa: "/ˈluːsɪd/", pos: "adj.", def: "Easy to understand.", ex: "Her lucid explanation won the deal." },
    { word: "Meticulous", ipa: "/məˈtɪkjələs/", pos: "adj.", def: "Extremely careful and precise.", ex: "He is meticulous about citations." },
    { word: "Novel", ipa: "/ˈnɒvəl/", pos: "adj.", def: "New and original.", ex: "It was a novel use of UPI rails." },
    { word: "Obstinate", ipa: "/ˈɒbstɪnət/", pos: "adj.", def: "Stubbornly refusing to change.", ex: "Obstinate buyers eventually walked away." },
    { word: "Plausible", ipa: "/ˈplɔːzəbl/", pos: "adj.", def: "Seeming reasonable or true.", ex: "Give me a plausible 3-year forecast." },
    { word: "Reluctant", ipa: "/rɪˈlʌktənt/", pos: "adj.", def: "Unwilling, hesitant.", ex: "He was reluctant to drop the feature." },
    { word: "Scrutinise", ipa: "/ˈskruːtɪnaɪz/", pos: "verb", def: "Examine carefully.", ex: "Investors will scrutinise every metric." },
    { word: "Tedious", ipa: "/ˈtiːdiəs/", pos: "adj.", def: "Boring and slow.", ex: "Manual data entry is tedious — automate it." },
    { word: "Vivid", ipa: "/ˈvɪvɪd/", pos: "adj.", def: "Strikingly clear or bright.", ex: "Use vivid examples in your story." },
    { word: "Adamant", ipa: "/ˈædəmənt/", pos: "adj.", def: "Refusing to be persuaded.", ex: "She was adamant about the launch date." },
    { word: "Coherent", ipa: "/koʊˈhɪərənt/", pos: "adj.", def: "Logical and consistent.", ex: "Build a coherent narrative across slides." },
    { word: "Dubious", ipa: "/ˈdjuːbiəs/", pos: "adj.", def: "Doubtful, suspicious.", ex: "The numbers look dubious." },
    { word: "Eloquent", ipa: "/ˈɛləkwənt/", pos: "adj.", def: "Fluent and persuasive.", ex: "An eloquent closer seals interviews." },
    { word: "Resilient", ipa: "/rɪˈzɪliənt/", pos: "adj.", def: "Recovering quickly from setbacks.", ex: "Resilient founders bounce back fast." },
    { word: "Substantiate", ipa: "/səbˈstænʃieɪt/", pos: "verb", def: "Provide evidence for.", ex: "Substantiate every claim with a number." },
    { word: "Tenacity", ipa: "/təˈnæsɪti/", pos: "noun", def: "Persistent determination.", ex: "Her tenacity got the deal across the line." },
    { word: "Veracity", ipa: "/vəˈræsɪti/", pos: "noun", def: "Truthfulness.", ex: "We must verify the veracity of the source." },
    { word: "Whimsical", ipa: "/ˈwɪmzɪkəl/", pos: "adj.", def: "Playfully unusual.", ex: "The brand voice is whimsical, not corporate." },
    { word: "Yield", ipa: "/jiːld/", pos: "verb", def: "Produce or give up.", ex: "The model should yield 18% ROI." },
  ],
  "Consulting Lingo": [
    { word: "Holistic", ipa: "/hoʊˈlɪstɪk/", pos: "adj.", def: "Considering the whole, not just parts.", ex: "We took a holistic view of the supply chain." },
    { word: "Actionable", ipa: "/ˈækʃənəbl/", pos: "adj.", def: "Able to be acted upon.", ex: "Give me one actionable insight." },
    { word: "MECE", ipa: "/ˈmiːsi/", pos: "adj.", def: "Mutually exclusive, collectively exhaustive.", ex: "Make sure the buckets are MECE." },
    { word: "Hypothesis", ipa: "/haɪˈpɒθəsɪs/", pos: "noun", def: "A testable proposed answer.", ex: "Let's hypothesis-test before we model." },
    { word: "Boil down", ipa: "/bɔɪl daʊn/", pos: "verb", def: "Reduce to essentials.", ex: "Boil it down to one slide for the partner." },
    { word: "Drill down", ipa: "/drɪl daʊn/", pos: "verb", def: "Examine in greater detail.", ex: "Drill down into Q3 churn cohorts." },
    { word: "Frame", ipa: "/freɪm/", pos: "verb", def: "Define how to view a problem.", ex: "How would you frame this decision?" },
    { word: "Lever", ipa: "/ˈlɛvər/", pos: "noun", def: "Specific factor you can change.", ex: "Pricing is our strongest lever." },
    { word: "North Star", ipa: "/nɔːrθ stɑːr/", pos: "noun", def: "Single guiding metric.", ex: "Activated users is our North Star." },
    { word: "Sandbag", ipa: "/ˈsændbæɡ/", pos: "verb", def: "Deliberately understate targets.", ex: "Don't sandbag the forecast." },
    { word: "Sanity check", ipa: "/ˈsænɪti tʃɛk/", pos: "noun", def: "Quick test of reasonableness.", ex: "Run a sanity check on those margins." },
    { word: "Triangulate", ipa: "/traɪˈæŋɡjəleɪt/", pos: "verb", def: "Verify using multiple sources.", ex: "Triangulate revenue with 3 inputs." },
    { word: "Workstream", ipa: "/ˈwɜːrkstriːm/", pos: "noun", def: "A parallel area of project work.", ex: "Each workstream needs a lead." },
    { word: "Whiteboard", ipa: "/ˈwaɪtbɔːrd/", pos: "verb", def: "Brainstorm visually live.", ex: "Let's whiteboard the user flow." },
    { word: "Anchor", ipa: "/ˈæŋkər/", pos: "verb", def: "Set a reference point.", ex: "Anchor the discussion on customer pain." },
    { word: "Benchmark", ipa: "/ˈbɛntʃmɑːrk/", pos: "noun", def: "Standard for comparison.", ex: "Benchmark our NPS vs the top quartile." },
    { word: "Crisp", ipa: "/krɪsp/", pos: "adj.", def: "Sharp, brief, clear.", ex: "Make the recommendation crisp." },
    { word: "Directionally", ipa: "/dɪˈrɛkʃənəli/", pos: "adv.", def: "Roughly correct in trend.", ex: "Directionally, we're aligned." },
    { word: "Granularity", ipa: "/ˌɡrænjəˈlærɪti/", pos: "noun", def: "Level of detail.", ex: "Add granularity at the segment level." },
    { word: "Insightful", ipa: "/ˈɪnsaɪtfʊl/", pos: "adj.", def: "Showing deep understanding.", ex: "That's an insightful angle on churn." },
    { word: "Mutually exclusive", ipa: "/ˈmjuːtʃuəli ɪkˈskluːsɪv/", pos: "adj.", def: "Cannot overlap.", ex: "Keep the categories mutually exclusive." },
    { word: "Plug-and-play", ipa: "/plʌɡ ænd pleɪ/", pos: "adj.", def: "Works without setup.", ex: "We need a plug-and-play module." },
    { word: "Sharpen", ipa: "/ˈʃɑːrpən/", pos: "verb", def: "Make clearer or more precise.", ex: "Sharpen the storyline before the readout." },
    { word: "Synthesise", ipa: "/ˈsɪnθəsaɪz/", pos: "verb", def: "Combine ideas into a clear whole.", ex: "Synthesise the interviews into 3 themes." },
    { word: "Throughput", ipa: "/ˈθruːpʊt/", pos: "noun", def: "Volume processed per unit time.", ex: "Throughput doubled after automation." },
    { word: "Top-down", ipa: "/tɒp daʊn/", pos: "adj.", def: "Starting from the big picture.", ex: "Run a top-down market sizing." },
    { word: "Bottom-up", ipa: "/ˈbɒtəm ʌp/", pos: "adj.", def: "Built from individual units.", ex: "Validate with a bottom-up build." },
    { word: "Value lever", ipa: "/ˈvæljuː ˈlɛvər/", pos: "noun", def: "Factor that drives value creation.", ex: "Pricing is the biggest value lever here." },
    { word: "War room", ipa: "/wɔːr ruːm/", pos: "noun", def: "Dedicated crisis workspace.", ex: "Set up a war room for the launch week." },
    { word: "Zero-based", ipa: "/ˈzɪəroʊ beɪst/", pos: "adj.", def: "Built from scratch, not last year.", ex: "Do a zero-based budgeting exercise." },
  ],
};

// Build the Random Mix dynamically (excludes itself).
const realDecks = Object.keys(VOCAB_WORDS);
VOCAB_WORDS[RANDOM_TRACK] = realDecks.flatMap((d) => VOCAB_WORDS[d]);

const realTopicCats = Object.keys(TOPICS);
TOPICS[RANDOM_TRACK] = realTopicCats.flatMap((c) => TOPICS[c]);
